[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CopyTrade"
authors = [{name = "Cuongitl", email = "https://t.me/Cuongitl"}]
dynamic = ["version", "description"]
